#!/usr/bin/sh

# Autostart applications
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x steam > /dev/null || steam &
pgrep -x chromium-browser-privacy > /dev/null || chromium-browser-privacy &
pgrep -x telegram-desktop > /dev/null || telegram-desktop &
pgrep -x vim > /dev/null || kitty --class Vim vim &
pgrep -x aerc > /dev/null || kitty --class aerc aerc &
pgrep -x redshift > /dev/null || redshift &
feh --bg-scale ~/.bg.png &
$HOME/.config/polybar/launch.sh &

# Monitor setup
bspc monitor DisplayPort-0 -d Vim Steam III IV V
bspc monitor HDMI-A-0 -d Chromium Telegram VIII IX X

# Desktop setup
bspc desktop Steam -l monocle

# Aesthetic & function
bspc config border_width             2
bspc config window_gap               0
bspc config focus_follows_pointer    true
bspc config pointer_follows_monitor  true
bspc config normal_border_color      "#3c3836"
bspc config active_border_color      "#282828"
bspc config focused_border_color     "#a89984"
bspc config split_ratio              0.62

# Application rules
bspc rule -a Vim desktop="Vim"
bspc rule -a Chromium-browser-privacy desktop="Chromium"
bspc rule -a Steam desktop="Steam"
bspc rule -a TelegramDesktop desktop="Telegram"
bspc rule -a aerc desktop="VIII"
