#!/usr/bin/sh

# Autostart applications
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x steam > /dev/null || steam &
pgrep -x firefox > /dev/null || firefox &
pgrep -x telegram-desktop > /dev/null || telegram-desktop &
pgrep -x redshift > /dev/null || redshift &
feh --bg-scale ~/.bg.png &
$HOME/.config/polybar/launch.sh &

# Monitor setup
bspc monitor DisplayPort-0 -d Spacemacs Steam III IV V
bspc monitor HDMI-A-0 -d Chromium Telegram cmus aerc irssi

# Desktop setup
bspc desktop Steam -l monocle

# Aesthetic & function
bspc config border_width           2
bspc config window_gap             0
bspc config focus_follows_pointer  true
bspc config normal_border_color    "#3c3836"
bspc config active_border_color    "#282828"
bspc config focused_border_color   "#a89984"
bspc config split_ratio            0.62

# Application rules
bspc rule -a ChromiumBrowserPrivacy desktop="Chromium"
bspc rule -a Steam desktop="Steam"
bspc rule -a TelegramDesktop desktop="Telegram"
bspc rule -a Emacs desktop="Spacemacs" state=tiled
