#!/usr/bin/sh

# Autostart applications
feh --bg-scale ~/.bg.png &
$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x steam > /dev/null || steam &
pgrep -x fireofx > /dev/null || firefox &
pgrep -x telegram-desktop > /dev/null || telegram-desktop &
pgrep -x nvim > /dev/null || kitty --class NVim nvim &
pgrep -x aerc > /dev/null || kitty --class aerc aerc &
pgrep -x newsboat > /dev/null || kitty --class newsboat newsboat &
pgrep -x calcurse > /dev/null || kitty --class calcurse calcurse &
pgrep -x tickrs > /dev/null || kitty --class tickrs tickrs &
pgrep -x buckle > /dev/null || buckle &
pgrep -x redshift > /dev/null || redshift &
startup.sh &

# Monitor setup
bspc monitor DisplayPort-0 -d Vim Steam III IV V
bspc monitor HDMI-A-0 -d Firefox Telegram Info IX X

# Desktop setup
bspc desktop Steam -l monocle
bspc desktop Info -l monocle

# Aesthetic & function
bspc config border_width             2
bspc config window_gap               0
bspc config focus_follows_pointer    true
bspc config pointer_follows_monitor  true
bspc config normal_border_color      "#3c3836"
bspc config active_border_color      "#282828"
bspc config focused_border_color     "#a89984"
bspc config split_ratio              0.62

# Application rules
bspc rule -a NVim desktop="NVim"
bspc rule -a Firefox desktop="Firefox"
bspc rule -a Steam desktop="Steam"
bspc rule -a TelegramDesktop desktop="Telegram"
bspc rule -a aerc desktop="Info"
bspc rule -a newsboat desktop="Info"
bspc rule -a calcurse desktop="Info"
bspc rule -a tickrs desktop="Info"
